comment-management API
swclabs/swix pull request #326
Opened 2024-08-23 03:41 UTC by anthony2704

This branch to develop comment-management API in Article Interface, included:

- [ ] Get Comment API
- [ ] Upload Comment API

2024-08-23 07:38 UTC, anthony2704 commented
@kyeranyo 
Please give a review for this update.

Thanks,
Khoa

2024-08-23 16:19 UTC, kyeranyo requested changes
implement comment repository

2024-09-01 14:06 UTC, kyeranyo commented
làm sai yêu cầu ở service và controller, chưa nắm được yêu cầu chức năng của comment, đặt sai ý nghĩa tên path /collections/comment  ???, collections có ý nghĩa gì trong bảng comment
![image](https://github.com/user-attachments/assets/cc9d07d4-357d-4051-9ea2-f6cee8233cfe)
position và content có ý nghĩa là gì trong cấu trúc 1 dòng bình luận ????

2024-09-01 14:12 UTC, kyeranyo commented
chưa mô tả được data được hiển thị cho người dùng qua (DTO), chưa thực hiện được flows của 1 comment được trả ra và được lưu như thế nào

2024-09-15 06:12 UTC, merged